### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/anova#2]
@melpetera in an email - 15/09/15

> Point 1 : paramètre Mode
> 
> Ce paramètre est prévu a priori pour pouvoir faire des anova au choix sur les lignes et colonnes (good point d'un point de vue purement stat). Mais du coup, comme maintenant il ne prend en entrée comme metadata que celles des samples (vu qu'orienté métabo), ben on ne peut plus les faire que pour les variables (une anova par variable). En metabo c'est ce qu'on fait, donc no problem, mais dans l'absolu du coup il faudrait :
> - soit supprimer le paramètre "Mode" (car du coup useless si on ne fait que des anova par variable) => easy to be done (c'est ce que je recommande perso)
> - soit garder la possibilité d'aussi faire des anova par sample (pour des gens qui voudraient utiliser l'outil pour autre chose que des données métabo) => plus de dev en perspective, et perso j'aurais plutôt tendance à dire que si quelqu'un veut faire ça sur des données non métabo, puisque ce n'est pas de la métabo il peut très bien mettre ses variables dans la sampleMetada et faire concorder sa datamatrix (après tout c'est son choix de venir utiliser des outils designés pour la métabo !)
> 
> Point 2 : Separators
> 
> A priori, vues nos conventions actuelles de format, il n'y a plus besoin des paramètres "Separator of columns" et "Decimal separator". 
> 
> Point 3 : Outputs
> 
> Actuellement, il y a deux fichiers en sortie :
> - un fichier correspondant à la dataMatrix avec en plus les colonnes de p-value
> - un fichier correspondant à la dataMatrix avec seulement les variables significatives
> 
> Sauf que du coup, ces deux fichiers ne permettent pas de chaîner ensuite avec d'autres outils. Et du coup, voici deux propositions :
> - Option minimaliste : au lieu de mettre les colonnes de pvalue dans la dataMatrix, les mettre dans la variableMetadata (nécessite de l'ajoute en input de l'outil), et supprimer la sortie filtrée. Il faut également ajouter une indicatrice supplémentaire en cas d'intéraction pour l'option Selection method (histoire que l'utilisateur puisse filtrer selon se critère avec Generic_Filter ensuite).
>   ¤ Point fort : un seul dataset de sortie
>   ¤ Point faible : il faut faire une étape de Generic Filter après, et ça fait un peu plus de dev à faire derrière (à noter qu'il faudrait alors aussi regrouper les paramètres Threshold et Selection Method sous la condition du N-way, donc un peu de changement dans l'agencement des paramètres)
> - Option tout compris : il faut également mettre les colonnes de pvalue dans le variableMetadata (à ajouter en input donc), mais on ajoute également en plus de la datamatrix filtrée déjà présente un variableMetadata filtré (pour pouvoir chainer ensuite avec d'autres outils). 
>   ¤ Point fort : pas besoin d'utiliser Generic_filter derrière ni de rajouter la création d'une indicatrice supplémentaire dans variableMetadata, et moins de modif d'interface
>   ¤ Point faible : plus de datasets en sortie
> 
> Point 4 : Working Example
> 
> Les sorties du Output files ne sont plus à jour. 
> Perso je recommande l'abandon de cette section, mais ce n'est que mon point de vue.

**Comment by melpetera** [comment]
Suite au PR #5 certains de ces points ont été traités. Du coup, listing des actions faites et restantes.

- [ ] Point 1 : **Choisir** entre garder "Mode" ou enlever "Mode"
- [ ] Point 2 : Enlever "Separator of column". **Choisir** si on enlève "Decimal separator" 
- [X] Point 3 : Revue de l'organisation des outputs
- [X] Point 4 : Abandon de la section "Working Example"

Concernant le point 2, je recommande d'enlever "Decimal separator" vu que le module est en anglais de toute façon. 

Concernant le point 1, je ne me souviens pas de ce dont je pouvais parler concernant du dev supplémentaire si on garde Mode... Je me demande si ce n'est pas simplement au niveau des messages d'erreur en cas de non-match des tables que ça bugait ? A vérifier, je peux lancer quelques tests quand la version du PR #5 sera sur la dev et voir de quoi il retourne. Et en fonction voir ce qu'on fait ?

Un avis sur ces 2 points @lecorguille ?

**Comment by lecorguille** [comment]
Pour le point 2, on pourrait en effet enlever "Separator of Column" mais tenter de le deviner:
Comme [ici](https://github.com/workflow4metabolomics/xcms/blob/xcms3_new_naming_msnbase/tools/xcms_merge/xcms_merge.r#L49)
```R
    sampleMetadata <- read.table(sampleMetadataFile, h=F, sep=";", stringsAsFactors=F)
    if (ncol(sampleMetadata) < 2) sampleMetadata <- read.table(sampleMetadataFile, h=F, sep="\t", stringsAsFactors=F)
    if (ncol(sampleMetadata) < 2) sampleMetadata <- read.table(sampleMetadataFile, h=F, sep=",", stringsAsFactors=F)
    if (ncol(sampleMetadata) < 2) {
        error_message="Your sampleMetadata file seems not well formatted. The column separators accepted are ; , and tabulation"
        print(error_message)
        stop(error_message)
    }
```

**Comment by melpetera** [comment]
Il y a une obligation d'être un tabular en input, donc de toute façon ce n'est pas censé être autre chose qu'une tabulation comme séparateur.

**Comment by lecorguille** [comment]
Si l'entrée vient du workflow W4M, c'est en effet des tabulations
Mais il faut imaginer y brancher d'autres outils en amont (hors metabo).

**Comment by melpetera** [comment]
Dans ce cas il faut laisser le paramètre "Separator of Column", et c'est le format tabular en input qu'il faut enlever.

Et du coup ça tranche aussi avec la question du "Mode" qu'il faut du coup laisser aussi.

**Comment by melpetera** [comment]
J'ai testé sur la dev pour la question du mode, et effectivement ça passe au rouge en cas de matrice inversée (j'imagine donc que c'est de ça dont je parlais à l'époque). J'investigue la question et propose un correctif.

**Comment by melpetera** [comment]
@lecorguille  j'ai trouvé le soucis et le correctif est assez simple, je vais le pusher directement sur la dev. Est-ce que j'en profite pour inclure de virer la spécification d'un tabular dans le XML pour clotûrer cette issue ?

**Comment by lecorguille** [comment]
C'est un peu à cause de vous, "les statisticiens", que j'ai rajouter ce `mode`.
A l'époque, vous vouliez que les tests soient fait sur les colonnes. 😖 
On peut le virer et ne garder que le mode `row`, ça me va.

Pour le séparateur, si tu veux, tu peux inclure cette fonction:
https://github.com/workflow4metabolomics/xcms/blob/284e6a94a9b88a97a1e5e97ad9b9519874c49901/tools/scripts/lib.r#L109
```R
# It allow different of field separators
getDataFrameFromFile <- function(filename, header=T) {
    myDataFrame <- read.table(filename, header=header, sep=";", stringsAsFactors=F)
    if (ncol(myDataFrame) < 2) myDataFrame <- read.table(filename, header=header, sep="\t", stringsAsFactors=F)
    if (ncol(myDataFrame) < 2) myDataFrame <- read.table(filename, header=header, sep=",", stringsAsFactors=F)
    if (ncol(myDataFrame) < 2) {
        error_message="Your tabular file seems not well formatted. The column separators accepted are ; , and tabulation"
        print(error_message)
        stop(error_message)
    }
    return(myDataFrame)
}
```

**Comment by melpetera** [comment]
Pour le mode, si on veut que l'outil soit aussi compatible hors métabo, il vaut mieux le laisser. C'est si on le focus 100% metabo qu'il vaut mieux l'enlever. De toute façon, j'ai corrigé le problème qu'il y avait avec "column" (voir c39d1ef). 

Pour le séparateur, du coup j'ai simplement ajouté la possibilité de prendre en entrée les CSV (voir 6e72f66). Et en cas de bad sniffing ça ira en gardant le paramètre de séparateur. 

Du coup normalement on est bon pour cette issue ! :)

**Comment by lecorguille** [comment]
Ok
Encore merci d'avoir sauver le soldat anova!
